package com.gibby.dungeon.mobs.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelPaladin extends ModelBase
{
    ModelRenderer Body;
    ModelRenderer Neck;
    ModelRenderer Body2;
    ModelRenderer LeftArm;
    ModelRenderer LeftLeg;
    ModelRenderer RightLeg;
    ModelRenderer RightArm;
    ModelRenderer Head;
    ModelRenderer Sword;
    ModelRenderer Shield;

    public ModelPaladin() {
        this.textureWidth = 128;
        this.textureHeight = 64;
        this.setTextureOffset("LeftArm.LeftArm1", 61, 0);
        this.setTextureOffset("LeftArm.LeftArm2", 0, 21);
        this.setTextureOffset("LeftArm.LeftArm3", 0, 21);
        this.setTextureOffset("LeftArm.LeftArm4", 28, 41);
        this.setTextureOffset("LeftArm.LeftArm5", 28, 41);
        this.setTextureOffset("Sword.Handle", 19, 0);
        this.setTextureOffset("Sword.Hilt4", 20, 0);
        this.setTextureOffset("Sword.Hilt1", 17, 2);
        this.setTextureOffset("Sword.Blade18", 0, 0);
        this.setTextureOffset("Sword.Hilt2", 0, 3);
        this.setTextureOffset("Sword.Blade17", 0, 0);
        this.setTextureOffset("Sword.Hilt3", 0, 0);
        this.setTextureOffset("Sword.Blade16", 0, 0);
        this.setTextureOffset("Sword.Blade1", 0, 0);
        this.setTextureOffset("Sword.Blade15", 0, 0);
        this.setTextureOffset("Sword.Blade2", 0, 0);
        this.setTextureOffset("Sword.Blade14", 0, 0);
        this.setTextureOffset("Sword.Blade3", 0, 1);
        this.setTextureOffset("Sword.Blade13", 0, 0);
        this.setTextureOffset("Sword.Blade4", 2, 2);
        this.setTextureOffset("Sword.Blade12", 0, 0);
        this.setTextureOffset("Sword.Blade5", 0, 0);
        this.setTextureOffset("Sword.Blade11", 0, 0);
        this.setTextureOffset("Sword.Blade6", 0, 2);
        this.setTextureOffset("Sword.Blade10", 0, 0);
        this.setTextureOffset("Sword.Blade7", 0, 2);
        this.setTextureOffset("Sword.Blade9", 0, 1);
        this.setTextureOffset("Sword.Blade8", 0, 0);
        this.setTextureOffset("LeftLeg.LeftLeg", 0, 47);
        this.setTextureOffset("LeftLeg.LeftLegArmor1", 0, 21);
        this.setTextureOffset("LeftLeg.LeftFoot1", 18, 54);
        this.setTextureOffset("LeftLeg.LeftFoot2", 18, 54);
        this.setTextureOffset("LeftLeg.LeftLegArmor1", 0, 21);
        this.setTextureOffset("RightLeg.LeftArm", 0, 47);
        this.setTextureOffset("RightLeg.RightLegArmor1", 0, 21);
        this.setTextureOffset("RightLeg.RightFoot1", 18, 54);
        this.setTextureOffset("RightLeg.RightFoot2", 18, 54);
        this.setTextureOffset("RightLeg.RightLegArmor1", 0, 21);
        this.setTextureOffset("RightArm.RightArm1", 61, 0);
        this.setTextureOffset("RightArm.RightArm3", 0, 21);
        this.setTextureOffset("RightArm.RightArm2", 0, 21);
        this.setTextureOffset("RightArm.RightArm4", 28, 41);
        this.setTextureOffset("RightArm.RightArm5", 28, 41);
        this.setTextureOffset("Shield.Shield1", 59, 13);
        this.setTextureOffset("Shield.Shield2", 59, 13);
        this.setTextureOffset("Shield.Shield3", 17, 2);
        this.setTextureOffset("Shield.Shield4", 59, 13);
        this.setTextureOffset("Shield.Shield1", 59, 13);
        this.setTextureOffset("Shield.Shield2", 59, 13);
        this.setTextureOffset("Shield.Shield2", 59, 13);
        this.setTextureOffset("Shield.Shield4", 59, 13);
        this.setTextureOffset("Shield.Shield3", 59, 13);
        this.setTextureOffset("Shield.Shield4", 59, 13);
        this.setTextureOffset("Shield.Shield3", 59, 13);
        this.setTextureOffset("Head.Head", 25, 21);
        this.setTextureOffset("Head.Helm1", 0, 21);
        this.setTextureOffset("Head.Helm2", 0, 21);
        this.setTextureOffset("Head.Helm3", 0, 21);
        this.setTextureOffset("Head.Helm2", 0, 21);
        this.setTextureOffset("Head.Helm2", 0, 21);
        this.setTextureOffset("Head.Helm1", 0, 21);
        (this.Body = new ModelRenderer(this, 84, 0)).addBox(-6.0f, 0.0f, 0.0f, 12, 12, 10);
        this.Body.setRotationPoint(0.0f, -7.0f, -6.0f);
        this.Body.setTextureSize(128, 64);
        this.Body.mirror = true;
        this.setRotation(this.Body);
        (this.Neck = new ModelRenderer(this, 0, 21)).addBox(0.0f, 0.0f, 0.0f, 4, 2, 4);
        this.Neck.setRotationPoint(-2.0f, -9.0f, -3.0f);
        this.Neck.setTextureSize(128, 64);
        this.Neck.mirror = true;
        this.setRotation(this.Neck);
        (this.Body2 = new ModelRenderer(this, 94, 7)).addBox(-4.0f, 6.0f, -4.0f, 8, 6, 8);
        this.Body2.setRotationPoint(0.0f, -1.0f, -1.0f);
        this.Body2.setTextureSize(128, 64);
        this.Body2.mirror = true;
        this.setRotation(this.Body2);
        (this.LeftArm = new ModelRenderer(this, "LeftArm")).setRotationPoint(-6.0f, -4.0f, -1.0f);
        this.setRotation(this.LeftArm);
        this.LeftArm.mirror = true;
        this.LeftArm.addBox("LeftArm1", -6.0f, 11.0f, -4.0f, 3, 4, 4);
        this.LeftArm.addBox("LeftArm2", -6.0f, -1.0f, -3.0f, 6, 2, 6);
        this.LeftArm.addBox("LeftArm3", -5.0f, -3.0f, -2.0f, 5, 2, 4);
        this.LeftArm.addBox("LeftArm4", -5.0f, 1.0f, -2.0f, 4, 5, 4);
        this.LeftArm.addBox("LeftArm5", -6.0f, 6.0f, -3.0f, 4, 5, 4);
        (this.Sword = new ModelRenderer(this, "Sword")).setRotationPoint(-5.0f, 13.0f, -4.0f);
        this.setRotation(this.Sword);
        this.Sword.mirror = true;
        this.Sword.addBox("Handle", 0.0f, 0.0f, -9.0f, 2, 2, 16);
        this.Sword.addBox("Hilt4", 0.0f, -1.0f, 7.0f, 2, 4, 2);
        this.Sword.addBox("Hilt1", -1.5f, 0.0f, -11.0f, 5, 2, 2);
        this.Sword.addBox("Blade18", 0.0f, -2.0f, -34.0f, 2, 3, 1);
        this.Sword.addBox("Hilt2", 2.0f, 0.0f, 6.0f, 1, 2, 4);
        this.Sword.addBox("Blade17", 1.0f, -1.0f, -31.0f, 1, 3, 3);
        this.Sword.addBox("Hilt3", -1.0f, 0.0f, 6.0f, 1, 2, 4);
        this.Sword.addBox("Blade16", 1.0f, -1.0f, -33.0f, 1, 3, 2);
        this.Sword.addBox("Blade1", -1.0f, -2.0f, -13.0f, 4, 6, 3);
        this.Sword.addBox("Blade15", 0.0f, -1.0f, -33.0f, 1, 3, 2);
        this.Sword.addBox("Blade2", -1.0f, -1.0f, -10.0f, 4, 4, 3);
        this.Sword.addBox("Blade14", 0.0f, 0.0f, -31.0f, 1, 3, 3);
        this.Sword.addBox("Blade3", 0.0f, 2.0f, -16.0f, 3, 3, 3);
        this.Sword.addBox("Blade13", 0.0f, 1.0f, -28.0f, 1, 3, 3);
        this.Sword.addBox("Blade4", -1.0f, -3.0f, -16.0f, 3, 3, 3);
        this.Sword.addBox("Blade12", 1.0f, -2.0f, -28.0f, 1, 3, 3);
        this.Sword.addBox("Blade5", 0.0f, 3.0f, -19.0f, 3, 3, 3);
        this.Sword.addBox("Blade11", 0.0f, -3.0f, -25.0f, 2, 3, 3);
        this.Sword.addBox("Blade6", -1.0f, -4.0f, -19.0f, 3, 3, 3);
        this.Sword.addBox("Blade10", 0.0f, -3.0f, -35.0f, 2, 3, 1);
        this.Sword.addBox("Blade7", 0.0f, 2.0f, -25.0f, 2, 3, 3);
        this.Sword.addBox("Blade9", 0.0f, 3.0f, -22.0f, 2, 3, 3);
        this.Sword.addBox("Blade8", 0.0f, -4.0f, -22.0f, 2, 3, 3);
        this.LeftArm.addChild(this.Sword);
        (this.LeftLeg = new ModelRenderer(this, "LeftLeg")).setRotationPoint(-4.0f, 9.0f, -1.0f);
        this.setRotation(this.LeftLeg);
        this.LeftLeg.mirror = true;
        this.LeftLeg.addBox("LeftLeg", -4.0f, 0.0f, -2.0f, 4, 13, 4);
        this.LeftLeg.addBox("LeftLegArmor1", -3.0f, -1.0f, -3.0f, 1, 14, 6);
        this.LeftLeg.addBox("LeftFoot1", -4.0f, 13.0f, -5.0f, 4, 2, 8);
        this.LeftLeg.addBox("LeftFoot2", -4.0f, 12.0f, -5.0f, 4, 1, 1);
        this.LeftLeg.addBox("LeftLegArmor1", -1.0f, -1.0f, -3.0f, 1, 6, 6);
        (this.RightLeg = new ModelRenderer(this, "RightLeg")).setRotationPoint(4.0f, 9.0f, -1.0f);
        this.setRotation(this.RightLeg);
        this.RightLeg.mirror = true;
        this.RightLeg.addBox("LeftArm", 0.0f, 0.0f, -2.0f, 4, 13, 4);
        this.RightLeg.addBox("RightLegArmor1", 2.0f, -1.0f, -3.0f, 1, 14, 6);
        this.RightLeg.addBox("RightFoot1", 0.0f, 13.0f, -5.0f, 4, 2, 8);
        this.RightLeg.addBox("RightFoot2", 0.0f, 12.0f, -5.0f, 4, 1, 1);
        this.RightLeg.addBox("RightLegArmor1", 0.0f, -1.0f, -3.0f, 1, 6, 6);
        (this.RightArm = new ModelRenderer(this, "RightArm")).setRotationPoint(6.0f, -4.0f, -1.0f);
        this.setRotation(this.RightArm);
        this.RightArm.mirror = true;
        this.RightArm.addBox("RightArm1", 2.0f, 7.0f, -8.0f, 3, 4, 4);
        this.RightArm.addBox("RightArm3", 0.0f, -1.0f, -3.0f, 6, 2, 6);
        this.RightArm.addBox("RightArm2", 0.0f, -3.0f, -2.0f, 5, 2, 4);
        this.RightArm.addBox("RightArm4", 1.0f, 1.0f, -2.0f, 4, 5, 4);
        this.RightArm.addBox("RightArm5", 2.0f, 6.0f, -4.0f, 4, 4, 5);
        (this.Shield = new ModelRenderer(this, "Shield")).setRotationPoint(-2.0f, 0.0f, -10.0f);
        this.setRotation(this.Shield);
        this.Shield.mirror = true;
        this.Shield.addBox("Shield1", -1.0f, -2.0f, 1.0f, 10, 20, 1);
        this.Shield.addBox("Shield2", -2.0f, -3.0f, 1.0f, 1, 9, 1);
        this.Shield.addBox("Shield3", 2.5f, 3.0f, -1.5f, 3, 8, 1);
        this.Shield.addBox("Shield4", 1.0f, 18.0f, 1.0f, 6, 2, 1);
        this.Shield.addBox("Shield1", 0.0f, 0.0f, 0.0f, 8, 16, 1);
        this.Shield.addBox("Shield2", 8.0f, -1.0f, 0.0f, 1, 8, 1);
        this.Shield.addBox("Shield2", 9.0f, -3.0f, 1.0f, 1, 9, 1);
        this.Shield.addBox("Shield4", 2.0f, 20.0f, 1.0f, 4, 2, 1);
        this.Shield.addBox("Shield3", -1.0f, -1.0f, 0.0f, 1, 8, 1);
        this.Shield.addBox("Shield4", 2.0f, 16.0f, 0.0f, 4, 2, 1);
        this.Shield.addBox("Shield3", 2.0f, 2.0f, -1.0f, 4, 12, 1);
        this.RightArm.addChild(this.Shield);
        (this.Head = new ModelRenderer(this, "Head")).setRotationPoint(0.0f, -9.0f, -1.0f);
        this.setRotation(this.Head);
        this.Head.mirror = true;
        this.Head.addBox("Head", -3.0f, -10.0f, -3.0f, 6, 10, 7);
        this.Head.addBox("Helm1", -3.0f, -11.0f, -3.0f, 6, 1, 6);
        this.Head.addBox("Helm2", 1.0f, -6.0f, -4.0f, 2, 6, 1);
        this.Head.addBox("Helm3", -3.0f, -6.0f, -4.0f, 2, 6, 1);
        this.Head.addBox("Helm2", 3.0f, -10.0f, -3.0f, 1, 10, 6);
        this.Head.addBox("Helm2", -4.0f, -10.0f, -3.0f, 1, 10, 6);
        this.Head.addBox("Helm1", -3.0f, -10.0f, -4.0f, 6, 3, 1);
    }

    public void render(final Entity entity, final float f, final float f1, final float f2, final float f3, final float f4, final float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.Body.render(f5);
        this.Neck.render(f5);
        this.Body2.render(f5);
        this.LeftArm.render(f5);
        this.LeftLeg.render(f5);
        this.RightLeg.render(f5);
        this.RightArm.render(f5);
        this.Head.render(f5);
    }

    private void setRotation(final ModelRenderer model) {
        model.rotateAngleX = (float) 0.0;
        model.rotateAngleY = (float) 0.0;
        model.rotateAngleZ = (float) 0.0;
    }

    public void setRotationAngles(final float par1, final float par2, final float par3, final float par4, final float par5, final float par6, final Entity par7Entity) {
        this.Head.rotateAngleY = par4 / 57.295776f;
        this.Head.rotateAngleX = par5 / 57.295776f;
        this.LeftLeg.rotateAngleX = -1.5f * this.func_78172_a(par1, 13.0f) * par2;
        this.RightLeg.rotateAngleX = 1.5f * this.func_78172_a(par1, 13.0f) * par2;
        this.LeftLeg.rotateAngleY = 0.0f;
        this.RightLeg.rotateAngleY = 0.0f;
        this.RightArm.rotateAngleX = MathHelper.cos(par1 * 0.3662f + 3.1415927f) * 2.0f * par2 * 0.5f;
        this.LeftArm.rotateAngleX = MathHelper.cos(par1 * 0.6662f) * 2.0f * par2 * 0.5f * 3.0f;
        this.RightArm.rotateAngleZ = 0.0f;
        this.LeftArm.rotateAngleZ = 0.0f;
    }

    private float func_78172_a(final float par1, final float par2) {
        return (Math.abs(par1 % par2 - par2 * 0.5f) - par2 * 0.25f) / (par2 * 0.25f);
    }
}
