

package com.gibby.dungeon.init;

import com.gibby.dungeon.Dungeons;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.util.WeightedRandomChestContent;
import net.minecraftforge.common.ChestGenHooks;

public class ChestSetup
{
    public static void addChestItems() {
        final ChestGenHooks vampireChest = ChestGenHooks.getInfo("Vampire");
        WeightedRandomChestContent stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVampire, 0, 1, 1, 20);
        vampireChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVampire, 0, 1, 1, 10);
        vampireChest.addItem(stack);
        final ChestGenHooks voidChest = ChestGenHooks.getInfo("VoidDungeon");
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 4, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverVoidDungeon, 0, 1, 1, 20);
        voidChest.addItem(stack);
        voidChest.addItem(stack);
        final ChestGenHooks netherChest = ChestGenHooks.getInfo("NetherStructure");
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 20);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 2, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverNetherStructure, 0, 1, 1, 10);
        netherChest.addItem(stack);
        final ChestGenHooks montaneChest = ChestGenHooks.getInfo("MontaneDungeon");
        stack = new WeightedRandomChestContent(Dungeons.setRare(new ItemStack(Dungeons.blackIronBoots)), 0, 1, 1);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.setRare(new ItemStack(Dungeons.torturedChainSword)), 0, 1, 1);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.setRare(new ItemStack(Dungeons.dungeonEyeSword)), 0, 1, 1);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.setRare(new ItemStack(Dungeons.frostySword)), 0, 1, 1);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 0, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 0, 1, 1);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontaneDungeon, 0, 1, 1, 10);
        montaneChest.addItem(stack);
        final ChestGenHooks montaneRichChest = ChestGenHooks.getInfo("MontaneRiches");
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.setRare(new ItemStack(Dungeons.frostySword)), 0, 1, 1);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.setLegendary(new ItemStack(Dungeons.blackIronSword)), 0, 1, 1);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.setLegendary(new ItemStack(Dungeons.blackIronBoots)), 0, 1, 1);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.setLegendary(new ItemStack(Dungeons.dungeonEyeSword)), 0, 1, 1);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.setLegendary(new ItemStack(Dungeons.corruptedBow)), 0, 1, 1);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.setRare(new ItemStack(Dungeons.blackIronBoots)), 0, 1, 1);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.setRare(new ItemStack(Dungeons.blackIronHelmet)), 0, 1, 1);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.setRare(new ItemStack(Dungeons.blackIronLeggings)), 0, 1, 1);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.setRare(new ItemStack(Dungeons.torturedChainSword)), 0, 1, 1);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.setRare(new ItemStack(Dungeons.dungeonEyeSword)), 0, 1, 1);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontagneRiche, 0, 0, 1, 10);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontagneRiche, 0, 1, 1, 10);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontagneRiche, 0, 1, 1, 10);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontagneRiche, 0, 1, 1, 10);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontagneRiche, 0, 0, 1, 4);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontagneRiche, 0, 1, 1, 10);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontagneRiche, 0, 1, 1, 10);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontagneRiche, 0, 1, 1, 10);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontagneRiche, 0, 0, 1, 10);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontagneRiche, 0, 1, 1, 10);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontagneRiche, 0, 1, 1, 10);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontagneRiche, 0, 1, 1, 10);
        montaneRichChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverMontagneRiche, 0, 1, 1, 10);
        montaneRichChest.addItem(stack);
        final ChestGenHooks beholderChest = ChestGenHooks.getInfo("Beholder");
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverBeholder, 0, 1, 1, 100);
        beholderChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverBeholder, 0, 1, 1, 50);
        beholderChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverBeholder, 0, 1, 1, 50);
        beholderChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverBeholder, 0, 1, 1, 50);
        beholderChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverBeholder, 0, 1, 1, 50);
        beholderChest.addItem(stack);
        stack = new WeightedRandomChestContent(Dungeons.randomItemGiverBeholder, 0, 1, 1, 50);
        beholderChest.addItem(stack);
    }
}
