

package com.gibby.dungeon.proxy;

import com.gibby.dungeon.*;
import com.gibby.dungeon.mobs.entityinstance.*;
import com.gibby.dungeon.mobs.model.*;
import com.gibby.dungeon.mobs.render.*;
import cpw.mods.fml.client.registry.RenderingRegistry;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelIronGolem;
import net.minecraft.client.model.ModelZombie;
import net.minecraft.client.renderer.entity.RenderSnowball;
import net.minecraft.init.Items;
import net.minecraftforge.client.MinecraftForgeClient;

public class ClientProxy extends CommonProxy
{
    @Override
    public void registerItemRenderers() {
        MinecraftForgeClient.registerItemRenderer(Dungeons.blackIronSword, new RenderBlackIronSword());
        MinecraftForgeClient.registerItemRenderer(Dungeons.orcWarWand, new RenderOrcWarWand());
        MinecraftForgeClient.registerItemRenderer(Dungeons.sunAxe, new RenderSunAxe());
        MinecraftForgeClient.registerItemRenderer(Dungeons.exawdusSmasher, new RenderExawdusSmasher());
    }

    @Override
    public void registerRenderInformation() {
        RenderingRegistry.registerEntityRenderingHandler(EntityGoblin.class, new RenderGoblin(new ModelZombie(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityBigStoneGolem.class, new RenderGolem(new ModelGolem(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityImp.class, new RenderImp(new ModelZombie(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntitySpecter.class, new RenderSpecter(new ModelSpecter(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityZombieWarlord.class, new RenderZombieWarlord());
        RenderingRegistry.registerEntityRenderingHandler(EntityEarthGolem.class, new RenderEarthGolem(new ModelEarthGolem(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityBandit.class, new RenderTheif(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityBanditBoss.class, new RenderBigTheif(new ModelBiped(), 1.0f));
        RenderingRegistry.registerEntityRenderingHandler(EntityTroll.class, new RenderTroll(new ModelTroll(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityShimmerman.class, new RenderShimmerman(new ModelShimmerman(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityCyclops.class, new RenderCyclops(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityStoneGolem.class, new RenderStoneGolem(new ModelIronGolem(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityTyphoon.class, new RenderTyphoon());
        RenderingRegistry.registerEntityRenderingHandler(EntitySandstorm.class, new RenderSandstorm());
        RenderingRegistry.registerEntityRenderingHandler(EntityVoidFiend.class, new RenderVoidFiend());
        RenderingRegistry.registerEntityRenderingHandler(EntityBlizzard.class, new RenderBlizzard());
        RenderingRegistry.registerEntityRenderingHandler(EntityTornado.class, new RenderTornado());
        RenderingRegistry.registerEntityRenderingHandler(EntitySpirit.class, new RenderTheif(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntitySkeletalMage.class, new RenderSkeletalMage());
        RenderingRegistry.registerEntityRenderingHandler(EntityHermit.class, new RenderHermit(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityWarlock.class, new RenderWarlock(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityEarthMage.class, new RenderHermit(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityNecro.class, new RenderNecro(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityIceMage.class, new RenderIceMage(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntitySapientWarrior.class, new RenderSapient(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityBlackKnight.class, new RenderBlackKnight(new ModelKnight(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityHannibal.class, new RenderHannibal(new ModelHannibal(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityRemnant.class, new RenderRemnant(new Modeldaybreak(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityVoidLord.class, new RenderVoidLord(new ModelVoidLord(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityDarkKnight.class, new RenderDarkKnight(new ModelKnight(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityNetherGhost.class, new RenderNetherGhost(new Ghost(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityNetherSoul.class, new RenderNetherSoul(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityNetherPigman.class, new RenderNetherPigman());
        RenderingRegistry.registerEntityRenderingHandler(EntitySapientMiner.class, new RenderSapient(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityAmethystMonster.class, new RenderAmethystMonster(new ModelAmethystMonster(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityStoneBot.class, new RenderStoneBot(new ModelIronGolem(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityVampire.class, new RenderVampire(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityLavaTroll.class, new RenderLavaTroll(new ModelMoltroll(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityLavaKnight.class, new RenderLavaKnight(new ModelKnight(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityNetherBadgerer.class, new RenderNetherBadgerer(new ModelCrystalBadger(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityBeholder.class, new RenderBeholder(new ModelBeholder(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityFireclops.class, new RenderFireclops(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityWitherSkeletonMinion.class, new RenderMiniChaosGolem(new ModelIronGolem(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityCrystalBadgerer.class, new RenderCrystalBadgerer(new ModelCrystalBadger(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityMoundTrader.class, new RenderMoundTrader());
        RenderingRegistry.registerEntityRenderingHandler(EntityAnchorTrader.class, new RenderMoundTrader());
        RenderingRegistry.registerEntityRenderingHandler(EntityTreeVillager.class, new RenderTreeVillager());
        RenderingRegistry.registerEntityRenderingHandler(EntityQuarryMaster.class, new RenderQuarryMaster());
        RenderingRegistry.registerEntityRenderingHandler(EntityGhostWither.class, new RenderGhostWither(new ModelGhostWither(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityChainMummy.class, new RenderChainMummy(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityEyeWarrior.class, new RenderEyeWarrior(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityYeti.class, new RenderYeti(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntitySnowGiant.class, new RenderSnowGiant(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityDeathBringer.class, new RenderDeathBringer(new ModelHannibal(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityDungeonBeast.class, new RenderDungeonBeast(new ModelDungeonBeast(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityDesertDragger.class, new RenderDesertDragger(new ModelDesertDragger(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityNetherWalker.class, new RenderNetherGolem(new ModelNetherGolem(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityFriendlyZombie.class, new RenderFriendlyZombie(new ModelZombie(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityIceShielder.class, new RenderIceShielder(new ModelIceShielder(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityOrc.class, new RenderOrc(new ModelOrc(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityOrcMage.class, new RenderOrcMage(new ModelOrcMage(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityOrcDefender.class, new RenderOrcDefender(new ModelOrcDefender(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityRockTroll.class, new RenderRockTroll(new ModelRockTroll(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityEarthRupturer.class, new RenderEarthRupturer(new ModelEarthRupturer(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityIceSpirit.class, new RenderIceSpirit(new ModelIceSpirit(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityUndefeatableStrength.class, new RenderUndefeatable(new ModelUndefeatable(), 0.5f, 1));
        RenderingRegistry.registerEntityRenderingHandler(EntityUndefeatableRegen.class, new RenderUndefeatable(new ModelUndefeatable(), 0.5f, 2));
        RenderingRegistry.registerEntityRenderingHandler(EntityUndefeatableResistance.class, new RenderUndefeatable(new ModelUndefeatable(), 0.5f, 3));
        RenderingRegistry.registerEntityRenderingHandler(EntitySapientEliteKnight.class, new RenderSapient(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntitySapientGeneral.class, new RenderSapient(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityMidnightShade.class, new RenderMidnightShade(new ModelMidnightShade(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntitySapientMage.class, new RenderSapient(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityCrystalTroll.class, new RenderCrystalTroll(new ModelRockTroll(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityCrystasis.class, new RenderCrystasis(new ModelCrystasis(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityCrystox.class, new RenderCrystox(new ModelCrystox(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityExawdus.class, new RenderExawdus(new ModelExawdus(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityCrystalliumGolem.class, new RenderCrystalliumGolem(new ModelCrystalliumGolem(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityIronStar.class, new RenderSnowball(Dungeons.castIronStar));
        RenderingRegistry.registerEntityRenderingHandler(EntityProjectileBall.class, new RenderProjectileBall(Items.fire_charge));
        RenderingRegistry.registerEntityRenderingHandler(EntityExplosive.class, new RenderSnowball(Dungeons.cpurple));
        RenderingRegistry.registerEntityRenderingHandler(EntitySpit.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntitySodbuster.class, new RenderSnowball(Dungeons.cgreen));
        RenderingRegistry.registerEntityRenderingHandler(EntityShimmerPearl.class, new RenderSnowball(Dungeons.shimmerPearl));
        RenderingRegistry.registerEntityRenderingHandler(EntityWaterBall.class, new RenderSnowball(Dungeons.cblue));
        RenderingRegistry.registerEntityRenderingHandler(EntitySandBall.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityBlizzardBall.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityTornadoBall.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityBloodBall.class, new RenderSnowball(Items.fire_charge));
        RenderingRegistry.registerEntityRenderingHandler(EntityRedBall.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityGreenBall.class, new RenderSnowball(Dungeons.cgreen));
        RenderingRegistry.registerEntityRenderingHandler(EntityBlueBall.class, new RenderSnowball(Dungeons.cblue));
        RenderingRegistry.registerEntityRenderingHandler(EntityMiniFireBall.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityNetherDriller.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityNetherDrill.class, new RenderSnowball(Dungeons.corruptedNetherSoul));
        RenderingRegistry.registerEntityRenderingHandler(EntityVoidBomb.class, new RenderSnowball(Dungeons.cgreen));
        RenderingRegistry.registerEntityRenderingHandler(EntityVoidDisk.class, new RenderSnowball(Dungeons.voidCoin));
        RenderingRegistry.registerEntityRenderingHandler(EntityRupture.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityAntigravity.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityExplosionSnake.class, new RenderSnowball(Dungeons.cgray));
        RenderingRegistry.registerEntityRenderingHandler(EntityEnergy.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityBlackEnergy.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityColdWind.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityHealEffect.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityQuake.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityDarkWave.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityAmethystPortal.class, new RenderSnowball(Dungeons.corruptedMagicOrb));
        RenderingRegistry.registerEntityRenderingHandler(EntitySunsetPortal.class, new RenderSnowball(Dungeons.sunsetOrb));
        RenderingRegistry.registerEntityRenderingHandler(EntityBeholderSpawner.class, new RenderSnowball(Dungeons.corruptedNetherSoul));
        RenderingRegistry.registerEntityRenderingHandler(EntityCursedStone.class, new RenderSnowball(Dungeons.cursedStone));
        RenderingRegistry.registerEntityRenderingHandler(EntityWitherSpawner.class, new RenderSnowball(Items.nether_star));
        RenderingRegistry.registerEntityRenderingHandler(EntityRuneExplosion.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityThrowback.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityIceShieldBall.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityRedBouncer.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityBlueBeam.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityIcefire.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityIceWanderer.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntitySunProjectile.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityGroundShade.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntitySapientDeath.class, new RenderSnowball(Dungeons.dungeonDimensionSpawner));
        RenderingRegistry.registerEntityRenderingHandler(EntityCrystalBeam.class, new RenderSnowball(Dungeons.cpurple));
        RenderingRegistry.registerEntityRenderingHandler(EntityMontanePortal.class, new RenderSnowball(Dungeons.dungeonDimensionSpawner));
        RenderingRegistry.registerEntityRenderingHandler(EntityMagirockBall.class, new RenderSnowball(Dungeons.cpurple));
        RenderingRegistry.registerEntityRenderingHandler(EntityVoidrim.class, new RenderSnowball(Dungeons.cvoidrim));
        RenderingRegistry.registerEntityRenderingHandler(EntityExawdusSpawner.class, new RenderSnowball(Dungeons.corruptedMagicOrb));
        RenderingRegistry.registerEntityRenderingHandler(EntityEnchantEffect.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityCrystalToxic.class, new RenderSnowball(Dungeons.invisible));
        RenderingRegistry.registerEntityRenderingHandler(EntityVoidrockBall.class, new RenderSnowball(Dungeons.cgreen));
        RenderingRegistry.registerEntityRenderingHandler(EntityFusionBall.class, new RenderSnowball(Dungeons.magirockCharge));
        RenderingRegistry.registerEntityRenderingHandler(EntityCrystalliumPlainsPortal.class, new RenderSnowball(Dungeons.magicalOrb));
        RenderingRegistry.registerEntityRenderingHandler(EntityCrystalMeteor.class, new RenderSnowball(Dungeons.cpurple));
    }
}
